### ISSUE TITLE
No pg_dump in Docker image

### ISSUE THREAD

**Issue by gaspo53** [omegion/db-backup#50]
Hi! I think you missed to add pg_dump into the Dockerfile:

` / # db-backup s3 export --host=$DB_HOST --port=5432 --databases=$DATABASE_NAME --username=$DB_USER --password=$DB_PASSWORD --bucket=$BUCKET_NAME --logLevel=debug
time="14-12-2022 15:10:42" level=debug msg="Exporting database table with pg_dump"
Error: 'pg_dump': Execution failed: ` 

Checking the package installed (postgresql): https://pkgs.alpinelinux.org/contents?branch=v3.3&name=postgresql&arch=x86&repo=main

**Comment by omegion** [comment]
Hi,

I've changed the base image to `postgres` alpine: https://github.com/omegion/db-backup/commit/756e2787f2bcb3ec6b9873b9536247c701aa4456

It should be good now.
